module.exports = {
    apps: [{
        name: "quant-agentic-core",
        script: "main_agentic_clob.py",
        cwd: __dirname,
        interpreter: ".venv/bin/python",
        instances: 1,
        exec_mode: "fork",
        max_restarts: 10000,
        min_uptime: "10s",
        restart_delay: 5000,
        exp_backoff_restart_delay: 1000,
        max_memory_restart: "4G",
        error_file: "logs/pm2-error.log",
        out_file: "logs/pm2-out.log",
        log_date_format: "YYYY-MM-DD HH:mm:ss Z",
        merge_logs: true,
        autorestart: true,
        env: {
            NODE_ENV: "production",
            PYTHONUNBUFFERED: "1",
            CHAT_ID: "-1003714224501",
            TARGET_CHANNEL: "Lobstar",
            TELEGRAM_PRIVATE_CHAT_IDS: "7413500821",
            TELEGRAM_ADMIN_CHAT_IDS: "7413500821",
            TELEGRAM_SIGNALS: process.env.TELEGRAM_SIGNALS || "true",
            TELEGRAM_BROADCAST_ENABLED: process.env.TELEGRAM_BROADCAST_ENABLED || "1",
            TELEGRAM_BROADCAST_EDGE_THRESHOLD: process.env.TELEGRAM_BROADCAST_EDGE_THRESHOLD || "0.07",
            TELEGRAM_BROADCAST_MAX_PER_MINUTE: process.env.TELEGRAM_BROADCAST_MAX_PER_MINUTE || "3",
            TELEGRAM_BROADCAST_TICKERS: process.env.TELEGRAM_BROADCAST_TICKERS || "SOL,BTC,ETH",
            SECRET_SOURCE: process.env.SECRET_SOURCE || "auto",
            VAULT_ADDR: process.env.VAULT_ADDR || "false",
            VAULT_TOKEN: process.env.VAULT_TOKEN,
        },
    }, {
        name: "quant-agentic-api",
        script: ".venv/bin/uvicorn",
        args: "api.api_server:app --host 0.0.0.0 --port 8000 --log-level info",
        cwd: __dirname,
        interpreter: ".venv/bin/python",
        instances: 1,
        exec_mode: "fork",
        max_restarts: 10000,
        min_uptime: "10s",
        restart_delay: 5000,
        exp_backoff_restart_delay: 1000,
        error_file: "logs/pm2-api-error.log",
        out_file: "logs/pm2-api-out.log",
        log_date_format: "YYYY-MM-DD HH:mm:ss Z",
        merge_logs: true,
        autorestart: true,
        env: {
            NODE_ENV: "production",
            PYTHONUNBUFFERED: "1",
            SECRET_SOURCE: process.env.SECRET_SOURCE || "auto",
            VAULT_ADDR: process.env.VAULT_ADDR || "false",
            VAULT_TOKEN: process.env.VAULT_TOKEN,
            API_FEATURE_STORE_PATH: "data/api_feature_store.duckdb",
        },
    }, {
        name: "quant-agentic-dashboard",
        script: ".venv/bin/streamlit",
        args: "run api/dashboard.py --server.port 8501 --server.headless true",
        cwd: __dirname,
        interpreter: ".venv/bin/python",
        instances: 1,
        exec_mode: "fork",
        max_restarts: 10000,
        min_uptime: "10s",
        restart_delay: 5000,
        exp_backoff_restart_delay: 1000,
        error_file: "logs/pm2-dashboard-error.log",
        out_file: "logs/pm2-dashboard-out.log",
        log_date_format: "YYYY-MM-DD HH:mm:ss Z",
        merge_logs: true,
        autorestart: true,
        env: {
            NODE_ENV: "production",
            PYTHONUNBUFFERED: "1",
        },
    }]
};
