import argparse
import logging
import os
import sys
from typing import Any, Optional

from continuous_improvement.analyzer import CodeAnalyzer
from continuous_improvement.knowledge_base import KnowledgeBase
from continuous_improvement.test_improver import TestImprover
from continuous_improvement.skills import ALL_SKILLS

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [CI] %(name)s %(levelname)s %(message)s",
)
logger = logging.getLogger("CI_Agent")

PROJECT_ROOT = os.path.dirname(os.path.dirname(__file__))


class CIRegistry:
    def __init__(self, root: str = PROJECT_ROOT) -> None:
        self.root = root
        self.kb = KnowledgeBase()
        self.analyzer = CodeAnalyzer(root)
        self.test_improver = TestImprover(root)

    # ── Analysis ──

    def run_full_analysis(self) -> dict[str, Any]:
        logger.info("Starting full code analysis...")
        analysis = self.analyzer.analyze_all()
        report = self.analyzer.generate_report(analysis)
        analysis["report_text"] = report
        logger.info(f"Analysis complete. "
                     f"{len(analysis.get('duplicated_functions', []))} duplications, "
                     f"{len(analysis.get('missing_type_hints', []))} missing type hints")
        return analysis

    def analyze_skill(self, skill_name: str) -> list[dict[str, Any]]:
        skill = ALL_SKILLS.get(skill_name)
        if skill is None:
            available = list(ALL_SKILLS.keys())
            return [{"error": f"Unknown skill '{skill_name}'. Available: {', '.join(available)}"}]
        issues = skill.detect_issues()
        improvements = skill.suggest_improvements()
        return [
            {"skill": skill_name, "type": "issues", "items": issues},
            {"skill": skill_name, "type": "improvements", "items": improvements},
        ]

    # ── Knowledge Base ──

    def record_decision(self, category: str, component: str, description: str, rationale: str) -> None:
        self.kb.record_decision(category, component, description, rationale)

    def record_error(self, component: str, error_type: str, message: str, context: str = "") -> None:
        self.kb.record_error(component, error_type, message, context)

    def record_test_run(self, total: int, passed: int, failed: int, duration_s: float) -> None:
        self.kb.record_test_run(total, passed, failed, duration_s)

    def get_summary(self) -> dict:
        return self.kb.summary()

    # ── Test Improvements ──

    def find_test_gaps(self) -> dict[str, Any]:
        return self.test_improver.report_test_gaps()

    # ── Skill Suggestions ──

    def collect_improvement_suggestions(self, skill_filter: Optional[str] = None) -> list[dict[str, Any]]:
        results = []
        for name, skill in ALL_SKILLS.items():
            if skill_filter and name != skill_filter:
                continue
            suggestions = skill.suggest_improvements()
            for s in suggestions:
                s["skill"] = name
            results.extend(suggestions)
        return results

    # ── Report Generation ──

    def generate_consolidated_report(self) -> str:
        analysis = self.run_full_analysis()
        report = analysis.get("report_text", "")

        report += "\n\n## Test Gaps\n"
        gaps = self.find_test_gaps()
        report += f"Untested modules: {gaps['untested_count']}\n"
        for m in gaps["untested_modules"][:15]:
            report += f"  - {m}\n"
        report += f"Test suggestions from skills: {gaps['suggestion_count']}\n"

        report += "\n## Suggested Improvements\n"
        suggestions = self.collect_improvement_suggestions()
        for s in suggestions[:15]:
            report += f"  [{s['skill']}] [{s['priority']}] {s['component']}: {s['suggestion']}\n"

        report += "\n## Knowledge Base Summary\n"
        kb_summary = self.get_summary()
        report += f"  Decisions recorded: {kb_summary.get('decisions', 0)}\n"
        report += f"  Unresolved errors: {kb_summary.get('errors', {}).get('unresolved', 0)}\n"
        report += f"  Pending improvements: {kb_summary.get('improvements', {}).get('pending', 0)}\n"
        report += f"  Test runs logged: {kb_summary.get('test_runs', 0)}\n"

        report += "\n" + "=" * 60 + "\n"
        report += "  Generated by Continuous Improvement Agent\n"
        report += "=" * 60
        return report


def run_analysis(root: str = PROJECT_ROOT) -> dict[str, Any]:
    registry = CIRegistry(root)
    return registry.run_full_analysis()


def run_command(args: list[str]) -> str:
    registry = CIRegistry()
    if not args:
        return "Usage: ci-agent <command> [options]\nCommands: analyze, report, gaps, suggestions, skills, record-decision, record-error, record-test, summary"

    cmd = args[0]

    if cmd == "analyze":
        analysis = registry.run_full_analysis()
        return analysis.get("report_text", str(analysis))

    elif cmd == "report":
        return registry.generate_consolidated_report()

    elif cmd == "gaps":
        gaps = registry.find_test_gaps()
        lines = [f"Untested modules ({gaps['untested_count']}):"]
        for m in gaps["untested_modules"]:
            lines.append(f"  - {m}")
        lines.append(f"\nTest suggestions from skills ({gaps['suggestion_count']}):")
        for s in gaps["test_suggestions"][:10]:
            lines.append(f"  [{s.get('skill','?')}] {s['description']}")
            for tc in s.get("test_cases", [])[:5]:
                lines.append(f"      - {tc}")
        return "\n".join(lines)

    elif cmd == "suggestions":
        skill = args[1] if len(args) > 1 else None
        suggestions = registry.collect_improvement_suggestions(skill)
        lines = [f"Improvement suggestions ({'all skills' if not skill else skill}):"]
        for s in suggestions:
            lines.append(f"  [{s['priority']}] [{s['skill']}] {s['component']}: {s['suggestion']}")
            if s.get("impact"):
                lines.append(f"      Impact: {s['impact']}")
        return "\n".join(lines)

    elif cmd == "skills":
        lines = ["Available skills:"]
        for name, skill in ALL_SKILLS.items():
            lines.append(f"  {name}: {skill.description}")
            for pf in skill.priority_files[:3]:
                lines.append(f"      - {pf}")
        return "\n".join(lines)

    elif cmd == "record-decision" and len(args) >= 4:
        registry.record_decision(args[1], args[2], args[3], " ".join(args[4:]) if len(args) > 4 else "")
        return "Decision recorded."

    elif cmd == "record-error" and len(args) >= 3:
        registry.record_error(args[1], args[2], " ".join(args[3:]))
        return "Error recorded."

    elif cmd == "record-test" and len(args) >= 4:
        registry.record_test_run(int(args[1]), int(args[2]), int(args[3]), float(args[4]) if len(args) > 4 else 0.0)
        return "Test run recorded."

    elif cmd == "summary":
        s = registry.get_summary()
        lines = ["Knowledge Base Summary:"]
        for k, v in s.items():
            lines.append(f"  {k}: {v}")
        return "\n".join(lines)

    else:
        return f"Unknown command or insufficient args: '{cmd}'"


if __name__ == "__main__":
    result = run_command(sys.argv[1:])
    print(result)
