import logging
import os
from typing import Any, Optional

from continuous_improvement.skills import ALL_SKILLS

logger = logging.getLogger("CI_TestImprover")

PROJECT_ROOT = os.path.dirname(os.path.dirname(__file__))

TEST_TEMPLATE = '''"""Tests for {module_path} — auto-generated by CI TestImprover"""
import pytest
from unittest.mock import AsyncMock, MagicMock, patch


class Test{class_name}:
    """Test suite for {module_path}"""

{test_methods}
'''


class TestImprover:
    def __init__(self, root: str = PROJECT_ROOT) -> None:
        self.root = root

    def find_untested_modules(self) -> list[str]:
        test_dir = os.path.join(self.root, "tests")
        if not os.path.exists(test_dir):
            return []

        tested = set()
        for f in os.listdir(test_dir):
            if f.startswith("test_") and f.endswith(".py"):
                tested.add(f.replace("test_", "").replace(".py", ""))

        untested = []
        search_dirs = ["core", "execution", "user_data/strategies", "utils", "ledger", "mcp_agents", "telegram_scraper"]
        for sd in search_dirs:
            full = os.path.join(self.root, sd)
            if not os.path.exists(full):
                continue
            for f in os.listdir(full):
                if f.endswith(".py") and not f.startswith("_"):
                    module = f.replace(".py", "")
                    if module not in tested:
                        untested.append(f"{sd}/{module}")
        return sorted(untested)

    def collect_test_suggestions(self) -> list[dict[str, Any]]:
        suggestions = []
        for skill_name, skill in ALL_SKILLS.items():
            gen = skill.generate_tests()
            for g in gen:
                g["skill"] = skill_name
            suggestions.extend(gen)
        return suggestions

    def generate_test_file(self, module_path: str) -> Optional[str]:
        module_name = module_path.replace("/", ".").replace(".py", "")
        class_name = module_path.split("/")[-1].replace(".py", "").replace("_", " ").title().replace(" ", "")

        test_methods = []
        test_methods.append("""    def test_initialization(self) -> None:
        \"\"\"Verify module can be instantiated\"\"\"
        pass

    def test_nominal_case(self) -> None:
        \"\"\"Test happy path execution\"\"\"
        pass

    def test_edge_case_empty_input(self) -> None:
        \"\"\"Test behavior with empty/missing input\"\"\"
        pass

    def test_error_handling(self) -> None:
        \"\"\"Test graceful error handling\"\"\"
        pass
""")

        return TEST_TEMPLATE.format(
            module_path=module_path,
            class_name=class_name,
            test_methods="\n".join(test_methods),
        )

    def report_test_gaps(self) -> dict[str, Any]:
        untested = self.find_untested_modules()
        suggestions = self.collect_test_suggestions()

        return {
            "untested_modules": untested,
            "untested_count": len(untested),
            "test_suggestions": suggestions,
            "suggestion_count": len(suggestions),
        }
