REGIME_LOW_VOLATILITY = "LOW_VOLATILITY"
REGIME_HIGH_TREND_VOLATILITY = "HIGH_TREND_VOLATILITY"
REGIME_ERRATIC_VOLATILITY = "ERRATIC_VOLATILITY"

REGIME_SIZING_MULTIPLIER = {
    REGIME_LOW_VOLATILITY: 1.0,
    REGIME_HIGH_TREND_VOLATILITY: 0.6,
    REGIME_ERRATIC_VOLATILITY: 0.0,
}

EXECUTION_MODES = {"REPLAY", "PAPER", "SHADOW", "PROD"}

FUSION_MODES = {"platt_only", "isotonic_only", "ensemble"}

DEFAULT_MAKER_TIMEOUT = 5.0
DEFAULT_WS_RECONNECT_DELAY = 5
MAX_WS_RECONNECT_DELAY = 60
MATCH_ORDERS_SIGNATURE = "0xd2539b37"

POLYMARKET_MICROFISH_TICKERS = [
    "BTC",
    "ETH",
    "SOL",
    "TRUMP",
    "META",
    "BITCOIN",
    "ETHEREUM",
    "SOLANA",
]
