REGIME_LOW_VOLATILITY = "LOW_VOLATILITY"
REGIME_HIGH_TREND_VOLATILITY = "HIGH_TREND_VOLATILITY"
REGIME_ERRATIC_VOLATILITY = "ERRATIC_VOLATILITY"

REGIME_SIZING_MULTIPLIER = {
    REGIME_LOW_VOLATILITY: 1.0,
    REGIME_HIGH_TREND_VOLATILITY: 0.6,
    REGIME_ERRATIC_VOLATILITY: 0.0,
}

EXECUTION_MODES = {"REPLAY", "PAPER", "SHADOW", "PROD"}

FUSION_MODES = {"platt_only", "isotonic_only", "ensemble"}

DEFAULT_MAKER_TIMEOUT = 5.0
DEFAULT_WS_RECONNECT_DELAY = 5
MAX_WS_RECONNECT_DELAY = 60
MATCH_ORDERS_SIGNATURE = "0xd2539b37"

POLYMARKET_MICROFISH_TICKERS = [
    "BTC",
    "ETH",
    "SOL",
    "TRUMP",
    "META",
    "BITCOIN",
    "ETHEREUM",
    "SOLANA",
]

CONTINUOUS_MARKET_TICKERS_BINANCE = ["BTCUSDT", "ETHUSDT"]
CONTINUOUS_MARKET_TICKERS_YFINANCE = ["SPY", "QQQ"]
CONTINUOUS_PREDICTION_HORIZON = 3
CONTINUOUS_CANDLE_INTERVAL = "5m"

CONTINUOUS_FEATURE_NAMES = [
    "open", "high", "low", "close", "volume",
    "rsi_14", "macd", "macd_signal", "bb_upper", "bb_lower",
    "log_return_1", "log_return_3", "log_return_5",
    "spread_bps", "order_imbalance",
]
CONTINUOUS_TARGET_FEATURE = "close"
